version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8001" # Changed from 8001 to 8101 to avoid conflicts
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: "python3 main.py --config ./config.yaml llm"

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=https://raggenie-api.doyelai.com # Ensure the backend URL is correct
    ports:
      - "8092:5000"
    volumes:
      - ./ui:/app
    depends_on:
      - backend
